spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:~/h2/springbootdemo;

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#  messages:
#    basename: messages
#    encoding: utf-8

server:
  port: 9900